import { IZipPort } from '../../domain/ports/output/IZipPort';
import { IExportShopifyPort } from '../../domain/ports/input/IExportPort';
import { VariableStore } from '../../domain/entities/Variable';

/**
 * Use case: export the current Liquid project as a Shopify section zip.
 */
export class ExportShopifyUseCase implements IExportShopifyPort {
  constructor(private readonly zip: IZipPort) {}

  async execute(
    name:      string,
    markup:    string,
    css:       string,
    js:        string,
    variables: VariableStore,
  ): Promise<void> {
    const hasJs = js.trim().length > 0;
    const label = name
      .replace(/^livecode-/, '')
      .replace(/-/g, ' ')
      .replace(/\b\w/g, c => c.toUpperCase());

    const schemaSettings = Object.entries(variables.values).map(([k, v]) => {
      const type = variables.meta[k] ?? 'text';
      return {
        type: type === 'media' ? 'image_picker' : 'text',
        id:   k,
        label: k.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
        ...(type !== 'media' ? { default: v || '' } : {}),
      };
    });

    const schema = JSON.stringify(
      { name: label, tag: 'section', class: name, settings: schemaSettings, presets: [{ name: label }] },
      null,
      2,
    );

    let liquidFile = [
      `{{ '${name}.css' | asset_url | stylesheet_tag }}`,
      '',
      markup,
      '',
      '{% schema %}',
      schema,
      '{% endschema %}',
    ].join('\n');

    if (hasJs) {
      liquidFile += `\n\n{% javascript %}\n  // JS loaded via asset — see assets/${name}.js\n{% endjavascript %}`;
    }

    const readme = [
      `# ${label}`,
      '',
      'Generated by **Live Editor** · Shopify Section',
      '',
      '## Install',
      `1. Copy \`sections/${name}.liquid\` → theme \`sections/\``,
      `2. Copy \`assets/*\` → theme \`assets/\``,
      '3. Shopify Admin → Online Store → Themes → Customize',
      `4. Add **${label}** section to your template`,
    ].join('\n');

    const files = [
      { path: `sections/${name}.liquid`, content: `/* ${name} — Shopify Section */\n/* Generated by Live Editor */\n\n${liquidFile}` },
      { path: `assets/${name}.css`,      content: `/* ${name} — Styles */\n/* Generated by Live Editor */\n\n${css}` },
      { path: 'README.md',               content: readme },
    ];

    if (hasJs) {
      files.push({ path: `assets/${name}.js`, content: `/* ${name} — Scripts */\n/* Generated by Live Editor */\n\n${js}` });
    }

    await this.zip.download(files, `${name}.zip`);
  }
}
