import { IZipPort } from '../../domain/ports/output/IZipPort';
import { IExportHtmlPort } from '../../domain/ports/input/IExportPort';

/**
 * Use case: export the current HTML/CSS/JS project as a static zip bundle.
 */
export class ExportHtmlUseCase implements IExportHtmlPort {
  constructor(private readonly zip: IZipPort) {}

  async execute(name: string, markup: string, css: string, js: string): Promise<void> {
    const hasJs = js.trim().length > 0;
    const label = name
      .replace(/^livecode-/, '')
      .replace(/-/g, ' ')
      .replace(/\b\w/g, c => c.toUpperCase());

    const indexHtml = [
      '<!DOCTYPE html>',
      '<html lang="en">',
      '<head>',
      '  <meta charset="UTF-8">',
      '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
      `  <title>${label}</title>`,
      `  <link rel="stylesheet" href="css/${name}.css">`,
      '</head>',
      '<body>',
      '',
      markup,
      '',
      hasJs ? `  <script src="js/${name}.js"><\/script>` : '',
      '</body>',
      '</html>',
    ]
      .filter(l => l !== undefined)
      .join('\n');

    const readmeLines = [
      `# ${label}`,
      '',
      'Generated by **Live Editor**',
      '',
      '## Structure',
      '```',
      `${name}/`,
      '├── index.html',
      '├── css/',
      `│   └── ${name}.css`,
      ...(hasJs ? ['├── js/', `│   └── ${name}.js`] : []),
      '└── README.md',
      '```',
      '',
      '## Usage',
      '1. Open `index.html` in your browser',
      `2. Edit \`css/${name}.css\` to change styles`,
      ...(hasJs ? [`3. Edit \`js/${name}.js\` to change behaviour`] : []),
      '4. Deploy folder to any static host (Netlify, Vercel, GitHub Pages)',
    ].join('\n');

    const files = [
      { path: `${name}/index.html`, content: indexHtml },
      { path: `${name}/css/${name}.css`, content: `/* ${name} — Styles */\n/* Generated by Live Editor */\n\n${css}` },
      { path: `${name}/README.md`, content: readmeLines },
    ];

    if (hasJs) {
      files.push({ path: `${name}/js/${name}.js`, content: `/* ${name} — Scripts */\n/* Generated by Live Editor */\n\n${js}` });
    }

    await this.zip.download(files, `${name}.zip`);
  }
}
