import { ProjectMap } from '../../domain/entities/Project';
import { VariableStore } from '../../domain/entities/Variable';
import { WATCH_SVG } from './watchSvg';

export const DEFAULT_PROJECTS: ProjectMap = {
  html: {
    markup: `<div class="card">
  <h1>Hello, Live Editor! 👋</h1>
  <p>
    Edit the panels on the left<br>
    and see changes in real time.
  </p>
  <button id="btn">Click me</button>
</div>`,
    css: `body {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  margin: 0;
  font-family: system-ui, sans-serif;
  background: #0f172a;
}

.card {
  background: #1e293b;
  color: #e2e8f0;
  padding: 2rem 2.5rem;
  border-radius: 16px;
  text-align: center;
}

h1 {
  margin: 0 0 0.75rem;
  font-size: 1.6rem;
}

p {
  color: #94a3b8;
  margin: 0 0 1.25rem;
  line-height: 1.6;
}

button {
  background: #6366f1;
  color: #fff;
  border: none;
  padding: 0.6rem 1.4rem;
  border-radius: 8px;
  font-size: 1rem;
  cursor: pointer;
  transition: background 0.2s;
}

button:hover {
  background: #818cf8;
}`,
    js: `document.getElementById('btn').addEventListener('click', function () {
  this.textContent = 'It works!';

  setTimeout(function () {
    document.getElementById('btn').textContent = 'Click me';
  }, 1500);
});`,
  },

  liquid: {
    markup: `{% comment %}
  Shopify Section — Product Card
  Generated by Live Editor
{% endcomment %}

<section class="lc-section">
  <div class="lc-card">

    {% if show_badge %}
      <span class="lc-badge">{{ badge_label }}</span>
    {% endif %}

    <div class="lc-media">
      {% if product_image != blank %}
        <img src="{{ product_image }}" alt="{{ product_title }}" />
      {% else %}
        ${WATCH_SVG}
      {% endif %}
    </div>

    <div class="lc-body">
      <p class="lc-vendor">{{ product_vendor }}</p>
      <h2 class="lc-title">{{ product_title }}</h2>

      <div class="lc-pricing">
        {% if compare_price %}
          <span class="lc-compare">{{ compare_price }}</span>
        {% endif %}
        <span class="lc-price">{{ product_price }}</span>
      </div>

      <p class="lc-description">{{ product_description }}</p>

      {% if product_available %}
        <button class="lc-btn-atc" id="atc-btn">Add to cart</button>
      {% else %}
        <button class="lc-btn-atc lc-sold-out" disabled>Sold out</button>
      {% endif %}
    </div>

  </div>
</section>`,
    css: `*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #f7f7f9;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

.lc-section { padding: 2rem; width: 100%; max-width: 380px; }

.lc-card {
  background: #fff;
  border-radius: 16px;
  overflow: hidden;
  box-shadow: 0 2px 16px rgba(0,0,0,0.08);
  position: relative;
}

.lc-badge {
  position: absolute; top: 14px; left: 14px; z-index: 2;
  background: #e53935; color: #fff;
  font-size: 10px; font-weight: 700; letter-spacing: 0.6px;
  text-transform: uppercase; padding: 3px 10px; border-radius: 20px;
}

.lc-media img { width: 100%; height: 260px; object-fit: cover; display: block; }
.lc-body { padding: 1.25rem 1.25rem 1.5rem; }
.lc-vendor { font-size: 11px; text-transform: uppercase; letter-spacing: 0.6px; color: #999; margin-bottom: 4px; }
.lc-title { font-size: 1.15rem; font-weight: 700; color: #1a202c; margin-bottom: 0.75rem; }
.lc-pricing { display: flex; align-items: center; gap: 10px; margin-bottom: 0.75rem; }
.lc-compare { font-size: 13px; color: #aaa; text-decoration: line-through; }
.lc-price { font-size: 1.25rem; font-weight: 700; color: #e53935; }
.lc-description { font-size: 13px; color: #718096; line-height: 1.6; margin-bottom: 1.25rem; }

.lc-btn-atc {
  width: 100%; padding: 0.75rem; background: #1a202c; color: #fff;
  border: none; border-radius: 10px; font-size: 14px; font-weight: 600;
  cursor: pointer; transition: background 0.2s;
}
.lc-btn-atc:hover:not([disabled]) { background: #2d3748; }
.lc-sold-out { background: #e2e8f0; color: #a0aec0; cursor: not-allowed; }`,
    js: `document.addEventListener('DOMContentLoaded', function () {
  var btn = document.getElementById('atc-btn');
  if (!btn) return;

  btn.addEventListener('click', function () {
    var orig = this.textContent;
    this.textContent = 'Added!';
    this.style.background = '#38a169';

    setTimeout(function () {
      btn.textContent = orig;
      btn.style.background = '';
    }, 1500);
  });
});`,
  },
};

export const DEFAULT_VARIABLES: VariableStore = {
  values: {
    product_title:       'Tissot Gentleman Powermatic 80',
    product_vendor:      'Tissot',
    product_price:       '$595.00',
    compare_price:       '$695.00',
    product_image:       '',
    badge_label:         'New',
    show_badge:          'true',
    product_available:   'true',
    product_description: 'Automatic Powermatic 80 with silicon balance spring. 40mm 316L stainless steel case, sapphire crystal, blue sunray dial and 80h power reserve.',
  },
  meta: {
    product_image: 'media',
  },
};
